version: '3.8'

services:
  relay-controller:
    build: .
    container_name: pialert-relay
    privileged: true
    devices:
      - /dev/gpiochip0
      - /dev/mem
    volumes:
      - /sys:/sys
    environment:
      - PIALERT_API_URL=http://webstatus.online/api/v1/alert-status
      - PIALERT_API_KEY=Bh_HaC9ss3UMH8WhLKRk-awpX23Fxzd9YkgM6H1V3P4
      - POLL_INTERVAL=30000
    ports:
      - "5000:5000"
    restart: unless-stopped
