services:
  relay-controller:
    build: .
    container_name: pialert-relay
    privileged: true
    devices:
      - /dev/gpiochip0:/dev/gpiochip0
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /sys/devices:/sys/devices
    environment:
      - PIALERT_API_URL=http://your-pialert-ip:8000/api/v1/alert-status
      - PIALERT_API_KEY=your-api-key-here
      - POLL_INTERVAL=30000
    ports:
      - "5000:5000"
    restart: unless-stopped
